version: '3.8'
services:
  server:
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data:/server/data
      - /TELEGRAM_BOT_TOKEN:/TELEGRAM_BOT_TOKEN
    build: server
    container_name: bot_youtube_tts
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    network_mode: "host"
    environment:
      - TZ=Europe/Moscow
      - OPENAI_API_KEY=OPENAI_API_KEY
      - TELEGRAM_BOT_TOKEN=TELEGRAM_BOT_TOKEN
